apiversion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: app1
sepc:
  project: default
  destination: 
    server: https://kubernetes.default.svc
    namspace: default
  source:
    repoURL: https://github.com/HARSHITHA-G-M/argocd.git
    path: chart1
    targetvision: master

